/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import javax.swing.JOptionPane;
import java.util.regex.*;  
/**
 *
 * @author adityapeen
 */
public class Tampilan extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan
     */
    public Tampilan() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihan = new javax.swing.JComboBox<>();
        textInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonConvert = new javax.swing.JButton();
        textOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biner ke Desimal", "Desimal ke Biner", "Desimal ke Oktal", "Desimal ke Hexadesimal" }));

        textInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Inputkan angka");

        buttonConvert.setText("Convert");
        buttonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConvertActionPerformed(evt);
            }
        });

        textOutput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(buttonConvert))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pilihan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textInput)
                        .addComponent(textOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonConvert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String Des2Bin(String desimal){
        int angka = Integer.parseInt(desimal);
        String biner = Integer.toBinaryString(angka);
        return biner;
    }
    
    public String Bin2Des(String biner){
        String desimal;
        desimal = String.valueOf(Integer.parseInt(biner, 2));
        return desimal;
    }
    
    public String Des2Hex(String desimal){
        int hex = Integer.parseInt(desimal);
        return Integer.toHexString(hex);
    }
    
    public String Des2Okt(String desimal){
        int okt = Integer.parseInt(desimal);
        return Integer.toOctalString(okt);
    }
    
    public boolean isBinary(String number){
        char[] ary = number.toCharArray();
        for(char c : ary) {
            if(!(c == '0' || c == '1')) return false;
        }
        return true;
    }
    public boolean isHuruf(String number){ 
        try{
            int angka = Integer.valueOf(number);
        }
        catch(NumberFormatException e){
            System.out.println(e);
            if(e.getMessage()!="") return false;
        }

        return true;
    }
    
    private void buttonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConvertActionPerformed
        // TODO add your handling code here:
        int sel;
        if(!textInput.getText().isEmpty()){
            String input = textInput.getText();
            if(input.contains(".")){
                JOptionPane.showMessageDialog(null, "Input mengandung titik (.)!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
            else if(!isHuruf(input)){
                JOptionPane.showMessageDialog(null, "Input bukan angka!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
            else{
                switch(pilihan.getSelectedIndex()){
                    case 0:
                        if(isBinary(input)){
                            textOutput.setText(Bin2Des(input));
                        }
                        else
                            JOptionPane.showMessageDialog(null, "Input bukan biner!",
                                    "Peringatan", JOptionPane.WARNING_MESSAGE);
                        break;
                    case 1:
                        textOutput.setText(Des2Bin(input));
                        break;
                    case 2:
                        textOutput.setText(Des2Okt(input));
                        break;
                    case 3:
                        textOutput.setText(Des2Hex(input));
                        break;
                }
            }
            
            
        }
        else{
            //sel = pilihan.getSelectedIndex();
            JOptionPane.showMessageDialog(null, "Input tidak boleh kosong!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConvert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> pilihan;
    private javax.swing.JTextField textInput;
    private javax.swing.JTextField textOutput;
    // End of variables declaration//GEN-END:variables
}
